services:
  django:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-end:/app  # Мапінг локального коду Django
      - ./front-end/build:/app/static  # Для статичних файлів
    ports:
      - "8000:8000" 
    environment:
      DJANGO_SETTINGS_MODULE: movies.settings
    # depends_on:
    #   - db
    networks:
      - django_graph_network

  react:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./front-end:/app  # Мапінг локального коду React
      - /app/node_modules  # Виключення node_modules
    ports:
      - "3000:3000"  # Відкриття порту для React
    environment:
      CHOKIDAR_USEPOLLING: "true"  # Для коректного відслідковування змін у файлах
    networks:
      - django_graph_network

  # db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: example_db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"  # Відкриття порту для MySQL
  #   networks:
  #     - django_graph_network

volumes:
  db_data:

networks:
  django_graph_network:
