apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-graphql-deployment
  labels:
    app: django-graphql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-graphql
  template:
    metadata:
      labels:
        app: django-graphql
    spec:
      containers:
      - name: django-graphql-container
        image: eleutherius69/django-graph:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "movies.settings"
        - name: PYTHONUNBUFFERED
          value: "1"
