apiVersion: v1
kind: Service
metadata:
  name: django-graphql-service
spec:
  selector:
    app: django-graphql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
